### ISSUE TITLE
ERROR in node_modules/ng-toggle-button/lib/ng-toggle.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

### ISSUE THREAD

**Issue by assmabenmussa** [vicmans/ng-toggle-button#16]
`This likely means that the library (ng-toggle-button) which declares NgToggleModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.`

Angular version: 

`
Angular CLI: 9.1.15
Node: 14.17.3
OS: win32 x64

Angular: 9.1.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.15
@angular-devkit/build-angular     0.901.15
@angular-devkit/build-optimizer   0.901.15
@angular-devkit/build-webpack     0.901.15
@angular-devkit/core              9.1.15
@angular-devkit/schematics        9.1.15
@angular/cli                      9.1.15
@ngtools/webpack                  9.1.15
@schematics/angular               9.1.15
@schematics/update                0.901.15
rxjs                              6.6.6
typescript                        3.8.3
webpack                           4.42.0`

**Comment by vicmans** [comment]
That problem was solved in the new version.

The previus version of the package is angular 8, it does not use Ivy

**Comment by assmabenmussa** [comment]
alright thank you very much
