### ISSUE TITLE
Please include a changelog for releases

### ISSUE THREAD

**Issue by siovene** [vicmans/ng-toggle-button#18]
Hi,
to try and stay up-to-date with my dependencies, I use renovatebot like many.

Unfortunately ng-toggle-button does not provide a changelog file, so even tho I have unit and e2e tests, I need to check your source code changes before upgrading to a newer version, and if the changes seem important, I need to test manually.

A simple changelog would really help me in determining whether or not I should test a new version manually or I can just trust the tests.

Thank you for this project and for considering this suggestion!

**Comment by vicmans** [comment]
Thanks you for the suggestion
