### ISSUE TITLE
[(ngModel)] doesn't work (Angular v13.0.x)

### ISSUE THREAD

**Issue by LeLunZ** [vicmans/ng-toggle-button#19]
Found a small problem. ngModel doesn't work on angular v13.
Why is this even needed? why not make _value_ a two way binding?

I tested this with the sample code locally. Can't share a stackblitz link because they don't support v13 yet.

> The property and event halves of the two-way binding 'ngModel' are not bound to the same target.
            Find more at https://angular.io/guide/two-way-binding#how-two-way-binding-works

>35     <ng-toggle [(ngModel)]="config.value"> </ng-toggle>
                    ~~~~~~~

>  node_modules/ng-toggle-button/lib/ng-toggle.component.d.ts:4:22
    4 export declare class NgToggleComponent implements OnInit, ControlValueAccessor {
                           ~~~~~~~~~~~~~~~~~
    The property half of the binding is to the 'NgToggleComponent' component.
  node_modules/@angular/forms/forms.d.ts:3649:22
    3649 export declare class NgModel extends NgControl implements OnChanges, OnDestroy {
                              ~~~~~~~
    The event half of the binding is to the 'NgModel' component.
  src/app/app.component.ts:28:16
    28   templateUrl: './app.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.

**Comment by vicmans** [comment]
Thank you for you feedback.

It was fixed the error caused by `ngModel` input in the component.
