### ISSUE TITLE
Updating value input prop does not update toggle

### ISSUE THREAD

**Issue by snowfrogdev** [vicmans/ng-toggle-button#34]
Programmatically updating the value of the `value` input property does not update the toggle. I think this may be related to the fact that the `onInput` method seems to be currently unused.

**Comment by vicmans** [comment]
it fixed but not released yet

**Comment by dave0688** [comment]
This still doesn't seem to work. Is there any progress?

**Comment by vicmans** [comment]
> This still doesn't seem to work. Is there any progress?

Yes, it works, look at this [example](https://stackblitz.com/edit/ng-toggle-button?file=src%2Fapp%2Fapp.component.html)

**Comment by dave0688** [comment]
Yes, sorry, it was a bug in my implementation. It's working as expected.
